version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: plant-backend
    ports:
      - "8000:8000"
#    restart: unless-stoppedd

  frontend:
    build:
      context: ./frontend
    container_name: plant-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
#    restart: unless-stopped
